# Normalização das Avaliações do IMDb

Este notebook apresenta o processo de normalização textual aplicado ao
dataset de avaliações de filmes do IMDb.

## Objetivo

Preparar os textos para as etapas posteriores de processamento,
encoding e representação numérica.

## Etapas realizadas

- Conversão para letras minúsculas;
- Remoção de tags HTML;
- Tratamento de entidades HTML;
- Normalização dos espaços em branco;
- Remoção de espaços extras no início e no final.

In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from preprocessing.normalization import normalize_text

In [2]:
RAW_DATA = PROJECT_ROOT / "data" / "raw" / "IMDB_Dataset_menor.csv"
PROCESSED_DATA = (
    PROJECT_ROOT / "data" / "processed" / "IMDB_Dataset_menor_normalizado.csv"
)

print("Dataset original:", RAW_DATA)
print("Dataset processado:", PROCESSED_DATA)

Dataset original: C:\Users\kaick\PycharmProjects\Projeto-IA-classificacaoSentimentosFilme\data\raw\IMDB_Dataset_menor.csv
Dataset processado: C:\Users\kaick\PycharmProjects\Projeto-IA-classificacaoSentimentosFilme\data\processed\IMDB_Dataset_menor_normalizado.csv

In [3]:
df = pd.read_csv(RAW_DATA)

print("Quantidade de linhas:", len(df))
print("Quantidade de colunas:", len(df.columns))

df.head()

Quantidade de linhas: 2000
Quantidade de colunas: 2

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.info()
df.columns
df.isnull().sum()
df["sentiment"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     2000 non-null   str
 1   sentiment  2000 non-null   str
dtypes: str(2)
memory usage: 31.4 KB

sentiment
positive    1005
negative     995
Name: count, dtype: int64

In [5]:
for i in range(3):
    original = df.loc[i, "review"]
    normalizado = normalize_text(original)

    print(f"--- Avaliação {i + 1} ---")
    print("ORIGINAL:")
    print(original)

    print("\nNORMALIZADO:")
    print(normalizado)

    print("\n" + "=" * 80 + "\n")

--- Avaliação 1 ---
ORIGINAL:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

NORMALIZADO:
one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me. the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word. it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away. i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

================================================================================

--- Avaliação 2 ---
ORIGINAL:
A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.

NORMALIZADO:
a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master's of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell's murals decorating every surface) are terribly well done.

================================================================================

--- Avaliação 3 ---
ORIGINAL:
I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I'd laughed at one of Woody's comedies in years (dare I say a decade?). While I've never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.

NORMALIZADO:
i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love. this was the most i'd laughed at one of woody's comedies in years (dare i say a decade?). while i've never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman. this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.

================================================================================

In [6]:
df_normalizado = df.copy()

df_normalizado["review"] = df_normalizado["review"].apply(normalize_text)

In [7]:
df_normalizado["review"].head(10)
#print("Original:", df.shape)
#print("Normalizado:", df_normalizado.shape)

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
5    probably my all-time favorite movie, a story o...
6    i sure would like to see a resurrection of a u...
7    this show was an amazing, fresh & innovative i...
8    encouraged by the positive comments about this...
9    if you like original gut wrenching laughter yo...
Name: review, dtype: str

In [8]:
PROCESSED_DATA.parent.mkdir(parents=True, exist_ok=True)

df_normalizado.to_csv(
    PROCESSED_DATA,
    index=False
)

print(f"Dataset normalizado salvo em:")
print(PROCESSED_DATA)

Dataset normalizado salvo em:
C:\Users\kaick\PycharmProjects\Projeto-IA-classificacaoSentimentosFilme\data\processed\IMDB_Dataset_menor_normalizado.csv

In [9]:
df_teste = pd.read_csv(PROCESSED_DATA)

print("Linhas:", len(df_teste))
print("Colunas:", list(df_teste.columns))

df_teste.head()

Linhas: 2000
Colunas: ['review', 'sentiment']

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive