# Encoding dos Rótulos de Sentimento

Este notebook apresenta a etapa de encoding dos rótulos de sentimento
das avaliações do IMDb.

## Objetivo

Transformar os rótulos textuais em valores numéricos para utilização
nas etapas posteriores de aprendizado de máquina.

### Mapeamento utilizado

- `negative` → `0`
- `positive` → `1`

Nesta etapa, apenas os rótulos de sentimento são codificados.
A representação numérica dos textos será realizada posteriormente.

In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from preprocessing.encoding import encode_sentiment

In [2]:
INPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "IMDB_Dataset_normalizado.csv"
)

OUTPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "IMDB_Dataset_encoded.csv"
)

print("Entrada:", INPUT_FILE)
print("Saída:", OUTPUT_FILE)

Entrada: c:\Users\User\Repositorios\Projeto-IA-classificacaoSentimentosFilme\data\processed\IMDB_Dataset_normalizado.csv
Saída: c:\Users\User\Repositorios\Projeto-IA-classificacaoSentimentosFilme\data\processed\IMDB_Dataset_encoded.csv

In [3]:
df = pd.read_csv(INPUT_FILE)

print("Quantidade de linhas:", len(df))
print("Quantidade de colunas:", len(df.columns))

df.head()

Quantidade de linhas: 50000
Quantidade de colunas: 2

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [4]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [5]:
df_encoded = df.copy()

df_encoded["sentiment"] = df_encoded["sentiment"].apply(
    encode_sentiment
)

df_encoded.head()

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          1
1  a wonderful little production. the filming tec...          1
2  i thought this was a wonderful way to spend ti...          1
3  basically there's a family where a little boy ...          0
4  petter mattei's "love in the time of money" is...          1

In [6]:
df_encoded["sentiment"].value_counts().sort_index()

sentiment
0    25000
1    25000
Name: count, dtype: int64

In [ ]:
sorted(df_encoded["sentiment"].unique())
#df_encoded.dtypes

review         str
sentiment    int64
dtype: object

In [9]:
print("Dataset original:", df.shape)
print("Dataset codificado:", df_encoded.shape)

Dataset original: (50000, 2)
Dataset codificado: (50000, 2)

In [10]:
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

df_encoded.to_csv(
    OUTPUT_FILE,
    index=False
)

print(f"Dataset codificado salvo em:\n{OUTPUT_FILE}")

Dataset codificado salvo em:
c:\Users\User\Repositorios\Projeto-IA-classificacaoSentimentosFilme\data\processed\IMDB_Dataset_encoded.csv

In [11]:
df_teste = pd.read_csv(OUTPUT_FILE)

print(df_teste.head())
print("\nValores de sentiment:")
print(df_teste["sentiment"].value_counts().sort_index())

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          1
1  a wonderful little production. the filming tec...          1
2  i thought this was a wonderful way to spend ti...          1
3  basically there's a family where a little boy ...          0
4  petter mattei's "love in the time of money" is...          1

Valores de sentiment:
sentiment
0    25000
1    25000
Name: count, dtype: int64